# Generated by Django 5.1.4 on 2025-01-03 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormBaseFieldCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('html_id', models.CharField(max_length=50)),
                ('html_name', models.CharField(max_length=50)),
                ('html_classes', models.CharField(blank=True, max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('email', models.CharField(max_length=255)),
                ('html_classes', models.CharField(blank=True, max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormCheckboxFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='akcmsplugin_contact_form.contactformbasefieldcms')),
                ('value', models.CharField(max_length=255)),
                ('checked', models.BooleanField()),
            ],
            bases=('akcmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormEmailFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='akcmsplugin_contact_form.contactformbasefieldcms')),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            bases=('akcmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormPhoneFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='akcmsplugin_contact_form.contactformbasefieldcms')),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('phone_pattern', models.CharField(blank=True, max_length=255)),
                ('phone_max_length', models.CharField(blank=True, max_length=4)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            bases=('akcmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormSubmitFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='akcmsplugin_contact_form.contactformbasefieldcms')),
                ('type', models.CharField(choices=[('button', 'Button'), ('input', 'Input')], max_length=255)),
            ],
            bases=('akcmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormTextAreaFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='akcmsplugin_contact_form.contactformbasefieldcms')),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('html_rows', models.CharField(blank=True, max_length=4)),
                ('html_cols', models.CharField(blank=True, max_length=4)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            bases=('akcmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormTextFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='akcmsplugin_contact_form.contactformbasefieldcms')),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            bases=('akcmsplugin_contact_form.contactformbasefieldcms',),
        ),
    ]
