# Generated by Django 5.1.4 on 2025-02-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0037_alter_cmsplugin_id_alter_globalpagepermission_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormCheckboxFieldCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('html_classes', models.CharField(blank=True, max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('checked', models.BooleanField(blank=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('email', models.CharField(max_length=255, verbose_name='From Email')),
                ('html_classes', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormEmailFieldCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('html_classes', models.CharField(blank=True, max_length=255)),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormPhoneFieldCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('html_classes', models.CharField(blank=True, max_length=255)),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('phone_pattern', models.CharField(blank=True, max_length=255)),
                ('phone_max_length', models.CharField(blank=True, max_length=4)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormSubmitFieldCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('html_classes', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('button', 'Button'), ('input', 'Input')], max_length=255)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormTextAreaFieldCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('html_classes', models.CharField(blank=True, max_length=255)),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('html_rows', models.CharField(blank=True, max_length=4)),
                ('html_cols', models.CharField(blank=True, max_length=4)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormTextFieldCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(max_length=255)),
                ('html_classes', models.CharField(blank=True, max_length=255)),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
