# Generated by Django 5.1.4 on 2025-01-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akcmsplugin_contact_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformbasefieldcms',
            name='html_id',
        ),
        migrations.RemoveField(
            model_name='contactformbasefieldcms',
            name='html_name',
        ),
    ]
