# Generated by Django 5.1.4 on 2025-02-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcmsplugin_contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformcms',
            name='email',
            field=models.CharField(default='hello@demomailtrap.com', max_length=255, verbose_name='From Email'),
        ),
    ]
