# Generated by Django 5.1.4 on 2025-01-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcmsplugin_contact_form', '0002_remove_contactformbasefieldcms_html_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformcms',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
